//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioZK.marcacion_1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="marcacion_1.ZHCM_WS_MARCACION_EMP")]
    public interface ZHCM_WS_MARCACION_EMP {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZhcmMarcacion no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZHCM_WS_MARCACION_EMP:ZhcmMarcac" +
            "ionRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServicioZK.marcacion_1.ZhcmMarcacionResponse1 ZhcmMarcacion(ServicioZK.marcacion_1.ZhcmMarcacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZHCM_WS_MARCACION_EMP:ZhcmMarcac" +
            "ionRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioZK.marcacion_1.ZhcmMarcacionResponse1> ZhcmMarcacionAsync(ServicioZK.marcacion_1.ZhcmMarcacionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZhcmMarcacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private E1hrkk1teup iMarcacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public E1hrkk1teup IMarcacion {
            get {
                return this.iMarcacionField;
            }
            set {
                this.iMarcacionField = value;
                this.RaisePropertyChanged("IMarcacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class E1hrkk1teup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string satzaField;
        
        private string teridField;
        
        private string ldateField;
        
        private string ltimeField;
        
        private string erdatField;
        
        private string ertimField;
        
        private string zauswField;
        
        private string pernrField;
        
        private string abwgrField;
        
        private string otypeField;
        
        private string plansField;
        
        private string usrupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Satza {
            get {
                return this.satzaField;
            }
            set {
                this.satzaField = value;
                this.RaisePropertyChanged("Satza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Terid {
            get {
                return this.teridField;
            }
            set {
                this.teridField = value;
                this.RaisePropertyChanged("Terid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Ldate {
            get {
                return this.ldateField;
            }
            set {
                this.ldateField = value;
                this.RaisePropertyChanged("Ldate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Ltime {
            get {
                return this.ltimeField;
            }
            set {
                this.ltimeField = value;
                this.RaisePropertyChanged("Ltime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Ertim {
            get {
                return this.ertimField;
            }
            set {
                this.ertimField = value;
                this.RaisePropertyChanged("Ertim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Zausw {
            get {
                return this.zauswField;
            }
            set {
                this.zauswField = value;
                this.RaisePropertyChanged("Zausw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
                this.RaisePropertyChanged("Pernr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Abwgr {
            get {
                return this.abwgrField;
            }
            set {
                this.abwgrField = value;
                this.RaisePropertyChanged("Abwgr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Otype {
            get {
                return this.otypeField;
            }
            set {
                this.otypeField = value;
                this.RaisePropertyChanged("Otype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Plans {
            get {
                return this.plansField;
            }
            set {
                this.plansField = value;
                this.RaisePropertyChanged("Plans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Usrup {
            get {
                return this.usrupField;
            }
            set {
                this.usrupField = value;
                this.RaisePropertyChanged("Usrup");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZhcmMarcacionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eInactivoField;
        
        private string ePernrField;
        
        private string eResultadoField;
        
        private string eStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EInactivo {
            get {
                return this.eInactivoField;
            }
            set {
                this.eInactivoField = value;
                this.RaisePropertyChanged("EInactivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EPernr {
            get {
                return this.ePernrField;
            }
            set {
                this.ePernrField = value;
                this.RaisePropertyChanged("EPernr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EResultado {
            get {
                return this.eResultadoField;
            }
            set {
                this.eResultadoField = value;
                this.RaisePropertyChanged("EResultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EStatus {
            get {
                return this.eStatusField;
            }
            set {
                this.eStatusField = value;
                this.RaisePropertyChanged("EStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZhcmMarcacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServicioZK.marcacion_1.ZhcmMarcacion ZhcmMarcacion;
        
        public ZhcmMarcacionRequest() {
        }
        
        public ZhcmMarcacionRequest(ServicioZK.marcacion_1.ZhcmMarcacion ZhcmMarcacion) {
            this.ZhcmMarcacion = ZhcmMarcacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZhcmMarcacionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServicioZK.marcacion_1.ZhcmMarcacionResponse ZhcmMarcacionResponse;
        
        public ZhcmMarcacionResponse1() {
        }
        
        public ZhcmMarcacionResponse1(ServicioZK.marcacion_1.ZhcmMarcacionResponse ZhcmMarcacionResponse) {
            this.ZhcmMarcacionResponse = ZhcmMarcacionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZHCM_WS_MARCACION_EMPChannel : ServicioZK.marcacion_1.ZHCM_WS_MARCACION_EMP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZHCM_WS_MARCACION_EMPClient : System.ServiceModel.ClientBase<ServicioZK.marcacion_1.ZHCM_WS_MARCACION_EMP>, ServicioZK.marcacion_1.ZHCM_WS_MARCACION_EMP {
        
        public ZHCM_WS_MARCACION_EMPClient() {
        }
        
        public ZHCM_WS_MARCACION_EMPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZHCM_WS_MARCACION_EMPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZHCM_WS_MARCACION_EMPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZHCM_WS_MARCACION_EMPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioZK.marcacion_1.ZhcmMarcacionResponse1 ServicioZK.marcacion_1.ZHCM_WS_MARCACION_EMP.ZhcmMarcacion(ServicioZK.marcacion_1.ZhcmMarcacionRequest request) {
            return base.Channel.ZhcmMarcacion(request);
        }
        
        public ServicioZK.marcacion_1.ZhcmMarcacionResponse ZhcmMarcacion(ServicioZK.marcacion_1.ZhcmMarcacion ZhcmMarcacion1) {
            ServicioZK.marcacion_1.ZhcmMarcacionRequest inValue = new ServicioZK.marcacion_1.ZhcmMarcacionRequest();
            inValue.ZhcmMarcacion = ZhcmMarcacion1;
            ServicioZK.marcacion_1.ZhcmMarcacionResponse1 retVal = ((ServicioZK.marcacion_1.ZHCM_WS_MARCACION_EMP)(this)).ZhcmMarcacion(inValue);
            return retVal.ZhcmMarcacionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioZK.marcacion_1.ZhcmMarcacionResponse1> ServicioZK.marcacion_1.ZHCM_WS_MARCACION_EMP.ZhcmMarcacionAsync(ServicioZK.marcacion_1.ZhcmMarcacionRequest request) {
            return base.Channel.ZhcmMarcacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioZK.marcacion_1.ZhcmMarcacionResponse1> ZhcmMarcacionAsync(ServicioZK.marcacion_1.ZhcmMarcacion ZhcmMarcacion) {
            ServicioZK.marcacion_1.ZhcmMarcacionRequest inValue = new ServicioZK.marcacion_1.ZhcmMarcacionRequest();
            inValue.ZhcmMarcacion = ZhcmMarcacion;
            return ((ServicioZK.marcacion_1.ZHCM_WS_MARCACION_EMP)(this)).ZhcmMarcacionAsync(inValue);
        }
    }
}
